spring:
  application:
    name: chat-service
  profiles:
    active: dev

server:
  port: 8083
  servlet:
    context-path: /chat

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.legacykeep: DEBUG
    org.springframework: INFO
